
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Osiguranje.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Imovina
{

    public int IDImovina { get; set; }

        [Display(Name = "Opis")]
        [Required(ErrorMessage = "Morate uneti opis")]
        public string Opis { get; set; }

        [Display(Name = "Vrednost")]
        [Required(ErrorMessage = "Morate uneti vrednost")]
        [RegularExpression("^\\d{2,10}$", ErrorMessage = "Unesite ispravnu vrednost")]
        public double Vrednost { get; set; }

    public int IDPolisa { get; set; }



    public virtual Polisa Polisa { get; set; }

}

}
