
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Osiguranje.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Klijent
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Klijent()
    {

        this.Polisas = new HashSet<Polisa>();

    }

        [Display(Name = "Maticni broj")]
        [Required(ErrorMessage = "Morate uneti maticni broj")]
        [RegularExpression("^[\\d]{13}$", ErrorMessage = "Unesite ispravnan maticni broj")]
        public string JMBG { get; set; }

        [Required(ErrorMessage = "Morate uneti ime")]
        [RegularExpression("^[a-zA-Z]{2,20}$", ErrorMessage = "Unesite ispravno ime")]
        public string Ime { get; set; }

        [Required(ErrorMessage = "Morate uneti prezime")]
        [RegularExpression("^[a-zA-Z]{2,20}$", ErrorMessage = "Unesite ispravno prezime")]
        public string Prezime { get; set; }

        [Required(ErrorMessage = "Morate uneti email adresu")]
        [RegularExpression("^[a-z\\d]+\\.?[a-z\\d]+\\@[a-z]{2,6}(\\.[a-z]{2,6})?\\.[a-z]{2,6}$", ErrorMessage = "Unesite validnu email adresu")]
        public string Email { get; set; }

        [Display(Name = "Broj telefona")]
        [Required(ErrorMessage = "Morate uneti broj telefona")]
        [RegularExpression("^(\\+[0-9]{2,3}||[0-9])?[0-9]{2}([\\/\\-])?[0-9]{4}[\\/\\-]?[0-9]{3,4}$", ErrorMessage = "Unesite validan broj telefona")]
        public string BrojTelefona { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Datum rodjenja")]
        [Required(ErrorMessage = "Morate uneti datum rodjenja")]
        public System.DateTime DatumRodjenja { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Polisa> Polisas { get; set; }

}

}
