

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Osiguranje.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class OsiguranjeEntities : DbContext
{
    public OsiguranjeEntities()
        : base("name=OsiguranjeEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Imovina> Imovinas { get; set; }

    public virtual DbSet<Klijent> Klijents { get; set; }

    public virtual DbSet<Korisnik> Korisniks { get; set; }

    public virtual DbSet<Objekat> Objekats { get; set; }

    public virtual DbSet<Polisa> Polisas { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

}

}

