
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Osiguranje.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Polisa
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Polisa()
    {

        this.Imovinas = new HashSet<Imovina>();

        this.Objekats = new HashSet<Objekat>();

    }


    public int IDPolisa { get; set; }

    public string JMBG { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Pocetak osiguranja")]
        public System.DateTime DatOd { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Kraj osiguranja")]
        public System.DateTime DatDo { get; set; }

        [Required(ErrorMessage = "Morate uneti tarifu")]
        [RegularExpression("^\\d{2,10}$", ErrorMessage = "Unesite ispravnu tarifu")]
        public string Tarifa { get; set; }

    public double Premija { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Imovina> Imovinas { get; set; }

    public virtual Klijent Klijent { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Objekat> Objekats { get; set; }

}

}
